install.packages(c('knitr', 'rmarkdown', 'e1071', 'survival', 'roxygen2', 'arrow'), repos='https://cloud.r-project.org/')
library(arrow)
arrow::install_arrow()
install.packages(c('crayon', 'praise', 'R6'), repos='https://cloud.r-project.org/')
install.packages('https://cloud.r-project.org/src/contrib/Archive/testthat/testthat_1.0.2.tar.gz', repos=NULL, type='source')
