#!/bin/bash

set -o pipefail
set -e
set -x

# Install Arrow R. Installs it here to make sure r-arrow is installed from conda (see environment.yml).
R -e "install.packages('arrow', repos='https://cloud.r-project.org/')"
# Also install other R libraries
R -e "install.packages(c('knitr', 'rmarkdown', 'e1071', 'survival', 'roxygen2'), repos='https://cloud.r-project.org/')"
R -e "install.packages(c('crayon', 'praise', 'R6'), repos='https://cloud.r-project.org/')"
R -e "install.packages('https://cloud.r-project.org/src/contrib/Archive/testthat/testthat_1.0.2.tar.gz', repos=NULL, type='source')"
R -e "install.packages(c('microbenchmark'), repos='https://cloud.r-project.org/')"
R -e "install.packages(c('tidyverse'), repos='https://cloud.r-project.org/')"

# Insall the latest Spark
git clone https://github.com/apache/spark.git
cd spark
./build/mvn -DskipTests -Psparkr -Phive package

